### ISSUE TITLE
Unable to find package System.Text.Utf8String.

### ISSUE THREAD

**Issue by tizzick** [antiufo/Shaman.Streams.Utf8#1]
I am getting the following error when I am trying to install the `Shaman.Streams.Utf8` package via nuget. Looks like the dependency `System.Text.Utf8String` is missing from nuget.

`Install-Package Shaman.Streams.Utf8  -Version 1.0.0.17`

> Install-Package : Unable to find package System.Text.Utf8String. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
> At line:1 char:1
> + Install-Package Shaman.Streams.Utf8
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : Package restore failed. Rolling back package changes for 'MyApp'.
> At line:1 char:1
> + Install-Package Shaman.Streams.Utf8
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Time Elapsed: 00:00:06.6420593

**Comment by antiufo** [comment]
That package hasn't been released on nuget.org yet. It's however available on myget.

Try to change your `NuGet.config` to something like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="CoreFxLab" value="https://dotnet.myget.org/F/dotnet-corefxlab/" />
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by tizzick** [comment]
Thanks, adding the `CoreFxLab` and `dotnet-core` sources fixed the problem.
